import React, { ReactElement } from 'react'
import Link from 'next/link'
import Head from 'next/head'
export default function Navbar() {
  
    
    return (
        <React.Fragment>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav role="navigation" aria-label="main navigation">
                <ul>
                <li><Link href="/">Home</Link></li>
                
                </ul>
              
            </nav>
        </React.Fragment>
    )
}
